#!/bin/bash
# Opens the Atlassian API token page and prints the scopes you need to select.

echo ""
echo "=== Jira MCP Power — Token Setup ==="
echo ""
echo "Opening the Atlassian API token page in your browser..."
echo ""
echo "When creating your token, select these scopes:"
echo ""
echo "  READ (for viewing issues):"
echo "    • read:issue:jira"
echo "    • read:issue-details:jira"
echo "    • read:issue-meta:jira"
echo "    • read:comment:jira"
echo "    • read:attachment:jira"
echo "    • read:project:jira"
echo "    • read:user:jira"
echo "    • read:field:jira"
echo "    • read:status:jira"
echo "    • read:jql:jira"
echo ""
echo "  WRITE (for transitioning/closing issues):"
echo "    • write:issue:jira"
echo ""
echo "Copy the generated token and paste it into your mcp.json config."
echo ""

open "https://id.atlassian.com/manage-profile/security/api-tokens"
